name: Test build action

on:
  push:
    branches:
    - build-test

jobs:
  web-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: jon-ionic/build-cap@41e7c8645a80a3b0c256a2a4579f45e9410a0b3c
      with:
        target-platform: android