name: Deploy Self-Hosted Live Update

on:
  push:
    branches:
    - main
    - 'update/**'
    - 'auto-deploy'

jobs:
  web-build:
    runs-on: ubuntu-latest

    env:
      IONIC_TOKEN: ${{ secrets.IONIC_TOKEN }}
      APP_ID: '7beb099c'
    
    steps:
    - name: Build Android on Appflow
      uses: ionic-team/appflow-build@v1.0.5
      with:
        token: ${{ secrets.IONIC_TOKEN }}
        app-id: 7beb099c
        platform: android
        build-type: debug
        upload-artifact: "AndroidBuild.zip"
        build-stack: "Linux - 2024.10"
